name: deploy-from-dockerhub

on:
  workflow_call:
    inputs:
      runner_name:
        required: true
        type: string
    secrets:
      envPAT:
        required: false
env:
  HUB_REPO_BACKEND: "${{ secrets.HUB_REPO_BACKEND }}"
  HUB_REPO_FRONTEND: "${{ secrets.HUB_REPO_FRONTEND }}"
  HUB_TOKEN: "${{ secrets.HUB_TOKEN }}"
  HUB_USER: "${{ secrets.HUB_USER }}"
jobs:
  deploy-from-dockerhub:
    runs-on: [self-hosted, '${{ inputs.runner_name }}']
    steps:
    -  run: |
        cp /var/cbr/.env ./.env
        docker compose -f docker-compose.yml -f docker-compose.deploy.yml pull
        docker compose -f docker-compose.yml -f docker-compose.deploy.yml up -d
        docker image prune -f
        bash -c 'sleep 15'
        docker exec cbr_django python manage.py migrate
        docker images
        docker ps -a
        docker volume ls
