name: export_image_tag

on:
  workflow_call:
    inputs:
      runner_tag:
        required: true
        type: string
      ci_commit_sha:
        required: true
        type: string
    secrets:
      secrets:
        required: true      
env:
  HUB_REPO_BACKEND: "${{ secrets.HUB_REPO_BACKEND }}"
  HUB_REPO_FRONTEND: "${{ secrets.HUB_REPO_FRONTEND }}"
  HUB_TOKEN: "${{ secrets.HUB_TOKEN }}"
  HUB_USER: "${{ secrets.HUB_USER }}"
jobs:
  export_image_tag:
    runs-on: [self-hosted, '${{ inputs.runner_tag }}']
    steps:
    - uses: actions/checkout@v3.0.0
      with:
        fetch-depth: 50
    - run: |
        echo "Commit SHA:                         = ${{ inputs.ci_commit_sha }}"
        export IMAGE_TAG=v$(git show -s --format=%cs ${{ inputs.ci_commit_sha }}).`git rev-parse --short=8 ${{ inputs.ci_commit_sha }}`
        echo "Docker hub user ='$HUB_USER',     version='$IMAGE_TAG'"
        echo "Full tag (backend) is               = $HUB_USER/$HUB_REPO_BACKEND:$IMAGE_TAG"
        echo "Full tag (rev-proxy & frontend) is  = $HUB_USER/$HUB_REPO_FRONTEND:$IMAGE_TAG"
        docker images
