name: 415-hha_cbr/cbr-platform

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  HUB_REPO_BACKEND: "${{ secrets.HUB_REPO_BACKEND }}"
  HUB_REPO_FRONTEND: "${{ secrets.HUB_REPO_FRONTEND }}"
  HUB_TOKEN: "${{ secrets.HUB_TOKEN }}"
  HUB_USER: "${{ secrets.HUB_USER }}"
  DEV_BRANCH: main
  STG_BRANCH: staging
  PROD_BRANCH: production
  NPM_VERSION: 7.19.0
jobs:
  prune:
    runs-on: [self-hosted, docker]
    steps:
    - run: docker compose down
  
  build-server:
    needs: [prune]
    runs-on: [self-hosted, docker]
    container:
      image: python:3.9.1-buster
    if: |
      ${{ github.event.pull_request.number }} != null) 
      || ${{ github.ref }} == $DEV_BRANCH 
      || ${{ github.ref }} == $STG_BRANCH 
      || ${{ github.ref }} == $PROD_BRANCH) 
      || ${{ github.event_name }} == "schedule" 
      || ${{ github.event_name }} == "web"
    timeout-minutes: 60
    services:
      test_postgres:
        image: postgres:13.1-alpine
    env:
      DOMAIN: example.com
      SECRET_KEY: test
      POSTGRES_DB: cbr
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_HOST: test_postgres
    steps:
    - uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 50
    - run: |
        ping test_postgres
        cd ./server
        pip install -r requirements.txt
        python -m black --check .
        python manage.py check
        python manage.py makemigrations --check
        python manage.py test

  export-image-tag-for-build-docker:
    if: ${{ github.ref }} == $DEV_BRANCH || ${{ github.event_name }} == "web"
    uses: vbui512/test/.github/workflows/export-image-tag.yml@b5cd22688a0294a86f425943b453d7a7b544375f
    with:
      config-path: deploy-dockerhub-shell
  


 
